"use strict";

// `say` is what the Czech voice reads for the letter on its own.
// Short vowels must sound short ("a", not "á"), otherwise A and Á sound the same.
const ALPHABET = [
  { letter: "A", say: "a", vowel: true },
  { letter: "Á", say: "á s čárkou", vowel: true, long: true },
  { letter: "B", say: "bé" },
  { letter: "C", say: "cé" },
  { letter: "Č", say: "čé" },
  { letter: "D", say: "dé" },
  { letter: "Ď", say: "ďé" },
  { letter: "E", say: "e", vowel: true },
  { letter: "É", say: "é s čárkou", vowel: true, long: true },
  { letter: "Ě", say: "e s háčkem", vowel: true },
  { letter: "F", say: "ef" },
  { letter: "G", say: "gé" },
  { letter: "H", say: "há" },
  { letter: "CH", say: "chá" },
  { letter: "I", say: "i", vowel: true },
  { letter: "Í", say: "í s čárkou", vowel: true, long: true },
  { letter: "J", say: "jé" },
  { letter: "K", say: "ká" },
  { letter: "L", say: "el" },
  { letter: "M", say: "em" },
  { letter: "N", say: "en" },
  { letter: "Ň", say: "eň" },
  { letter: "O", say: "o", vowel: true },
  { letter: "Ó", say: "ó s čárkou", vowel: true, long: true },
  { letter: "P", say: "pé" },
  { letter: "R", say: "er" },
  { letter: "Ř", say: "eř" },
  { letter: "S", say: "es" },
  { letter: "Š", say: "eš" },
  { letter: "T", say: "té" },
  { letter: "Ť", say: "ťé" },
  { letter: "U", say: "u", vowel: true },
  { letter: "Ú", say: "ú s čárkou", vowel: true, long: true },
  { letter: "Ů", say: "ů s kroužkem", vowel: true, long: true },
  { letter: "V", say: "vé" },
  { letter: "Y", say: "ypsilon", vowel: true },
  { letter: "Ý", say: "ypsilon s čárkou", vowel: true, long: true },
  { letter: "Z", say: "zet" },
  { letter: "Ž", say: "žet" },
  { letter: "Q", say: "kvé", foreign: true },
  { letter: "W", say: "dvojité vé", foreign: true },
  { letter: "X", say: "iks", foreign: true }
];
